- README.md
- exe/terraforming
- lib/terraforming.rb
- lib/terraforming/cli.rb
- spec/lib/terraforming/resource/ec2_spec.rb
- spec/lib/terraforming/resource/security_group_spec.rb
- spec/lib/terraforming/resource/vpc_spec.rb
- terraforming.gemspec
- Disable unimplemented resources
- Use [Thor](https://github.com/erikhuda/thor) for CLI
- Update README
> Update executable file

- lib/terraforming.rb
- lib/terraforming/resource.rb
- lib/terraforming/resource/db_parameter_group.rb
- lib/terraforming/resource/db_security_group.rb
- lib/terraforming/resource/db_subnet_group.rb
- lib/terraforming/resource/ec2.rb
- lib/terraforming/resource/elb.rb
- lib/terraforming/resource/rds.rb
- lib/terraforming/resource/s3.rb
- lib/terraforming/resource/security_group.rb
- lib/terraforming/resource/vpc.rb
To reduce "similar codes",
- Integrate main logic to `Terraforming::Resource.apply_template` method
- Move `Terraforming.template_path` to `Terraforming::Resource.template_path`
> Refactor tf method

- lib/terraforming/resource/vpc.rb
- lib/terraforming/template/tf/vpc.erb
- spec/lib/terraforming/resource/vpc_spec.rb
- `enable_dns_hostnames`
- `enable_dns_support`
> Include VPC attributes

- lib/terraforming/resource/db_parameter_group.rb
- lib/terraforming/resource/db_security_group.rb
- lib/terraforming/resource/db_subnet_group.rb
- lib/terraforming/resource/ec2.rb
- lib/terraforming/resource/elb.rb
- lib/terraforming/resource/network_acl.rb
- lib/terraforming/resource/rds.rb
- lib/terraforming/resource/s3.rb
- lib/terraforming/resource/security_group.rb
- lib/terraforming/resource/subnet.rb
- lib/terraforming/resource/vpc.rb
- lib/terraforming/util.rb
- spec/lib/terraforming/resource/db_parameter_group_spec.rb
- spec/lib/terraforming/resource/db_security_group_spec.rb
- spec/lib/terraforming/resource/db_subnet_group_spec.rb
- spec/lib/terraforming/resource/ec2_spec.rb
- spec/lib/terraforming/resource/elb_spec.rb
- spec/lib/terraforming/resource/network_acl_spec.rb
- spec/lib/terraforming/resource/rds_spec.rb
- spec/lib/terraforming/resource/s3_spec.rb
- spec/lib/terraforming/resource/security_group_spec.rb
- spec/lib/terraforming/resource/subnet_spec.rb
- spec/lib/terraforming/resource/vpc_spec.rb
from #34 
```ruby
module Terraforming::Util
end
```
```ruby
module Terraforming
module Util
end
end
```
> Fix module nesting declation

- lib/terraforming/template/tf/iam_group_policy.erb
- lib/terraforming/template/tf/iam_user_policy.erb
- spec/lib/terraforming/resource/iam_group_policy_spec.rb
- spec/lib/terraforming/resource/iam_user_policy_spec.rb
`EOF (end of file)` is not appropriate for non-file content.
`POLICY` is better.
> Change heredoc identifer to POLICY

- lib/terraforming/util.rb
- spec/lib/terraforming/resource/db_parameter_group_spec.rb
- spec/lib/terraforming/resource/db_security_group_spec.rb
- spec/lib/terraforming/resource/db_subnet_group_spec.rb
- spec/lib/terraforming/resource/ec2_spec.rb
- spec/lib/terraforming/resource/elb_spec.rb
- spec/lib/terraforming/resource/iam_group_policy_spec.rb
- spec/lib/terraforming/resource/iam_group_spec.rb
- spec/lib/terraforming/resource/iam_policy_spec.rb
- spec/lib/terraforming/resource/iam_user_policy_spec.rb
- spec/lib/terraforming/resource/iam_user_spec.rb
- spec/lib/terraforming/resource/network_acl_spec.rb
- spec/lib/terraforming/resource/rds_spec.rb
- spec/lib/terraforming/resource/route53_record_spec.rb
- spec/lib/terraforming/resource/route53_zone_spec.rb
- spec/lib/terraforming/resource/s3_spec.rb
- spec/lib/terraforming/resource/security_group_spec.rb
- spec/lib/terraforming/resource/subnet_spec.rb
- spec/lib/terraforming/resource/vpc_spec.rb
> Modules list hash

- lib/terraforming/resource/iam_role_policy.rb
- spec/lib/terraforming/resource/iam_role_policy_spec.rb
Correspond `primary id` value and `attribute id` value.
> Fix IAM role policy tfstate id

- spec/lib/terraforming/resource/route53_record_spec.rb
- spec/lib/terraforming/resource/route53_zone_spec.rb
- terraforming.gemspec
> Use aws-sdk gem v2.1.0

- lib/terraforming/resource/elb.rb
- lib/terraforming/template/tf/elb.erb
- spec/lib/terraforming/resource/elb_spec.rb
> Include either AZs or subnets in ELB tf

- lib/terraforming/resource/elb.rb
- lib/terraforming/template/tf/elb.erb
- spec/lib/terraforming/resource/elb_spec.rb
Updated elb.rb and elb.erb to properly output ELBs and their attributes. New outputs include tags, listeners, security groups, health checks, instances, and subnets.
> Elb tfstate fix

- lib/terraforming/resource/ec2.rb
- lib/terraforming/template/tf/ec2.erb
- spec/lib/terraforming/resource/ec2_spec.rb
from #93 
Generate appropriate tf and tfstate around VPC or non-VPC security groups of EC2 instance
> Modify EC2 security_groups

- lib/terraforming/resource/route53_record.rb
- lib/terraforming/template/tf/route53_record.erb
- spec/lib/terraforming/resource/route53_record_spec.rb
> updated resource name to include the record type

- lib/terraforming/resource/iam_group_policy.rb
- lib/terraforming/resource/iam_policy.rb
- lib/terraforming/resource/iam_role.rb
- lib/terraforming/resource/iam_role_policy.rb
- lib/terraforming/resource/iam_user_policy.rb
- lib/terraforming/resource/s3.rb
- lib/terraforming/template/tf/iam_group_policy.erb
- lib/terraforming/template/tf/iam_policy.erb
- lib/terraforming/template/tf/iam_role.erb
- lib/terraforming/template/tf/iam_role_policy.erb
- lib/terraforming/template/tf/iam_user_policy.erb
- lib/terraforming/template/tf/s3.erb
- lib/terraforming/util.rb
- spec/lib/terraforming/resource/s3_spec.rb
Close #100 
Add support for S3 bucket policy
- [AWS: aws_s3_bucket - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html)
> Support S3 bucket policy

- .travis.yml
> Run CI with the latest Ruby

- lib/terraforming.rb
- lib/terraforming/cli.rb
- lib/terraforming/resource/auto_scaling_group.rb
- lib/terraforming/template/tf/auto_scaling_group.erb
- spec/lib/terraforming/cli_spec.rb
- spec/lib/terraforming/resource/auto_scaling_group_spec.rb
> Support AutoScaling Group

- lib/terraforming/cli.rb
$ export AWS_REGION=ap-nottheast-1; terraforming s3 --profile myprofile
> Support `--profile` option

- lib/terraforming/resource/route53_zone.rb
- lib/terraforming/template/tf/route53_zone.erb
- spec/lib/terraforming/resource/route53_zone_spec.rb
Get the zone comment for a route53 zone.
Update rspec tests to handle zone comments.
> Get zone comment for route53 zone

- lib/terraforming/resource/iam_user.rb
This is just an initial PoC to show how to use the Ruby AWS SDK's paging
support. Would have to look into a better solution for the entire list
of resources.
This fixes #156 but should figure out a more generic solution for paging across the board here.
> Support paging for IAM user call

- README.md
It's what the Ruby SDK seems to expect. :)
> Use AWS_REGION, not AWS_DEFAULT_REGION.

- lib/terraforming/template/tf/elb.erb
- spec/lib/terraforming/resource/elb_spec.rb
> Missing tag name wrap on ELB resource

- lib/terraforming/resource/ec2.rb
- lib/terraforming/template/tf/ec2.erb
- spec/lib/terraforming/resource/ec2_spec.rb
:smile: fairly simple change. I don't do much Ruby these days, so please pardon me if it's less than idiomatic.
> Include EC2 placement group.

- lib/terraforming/resource/iam_group.rb
- lib/terraforming/resource/iam_policy.rb
- lib/terraforming/resource/iam_role.rb
> Fix paging for iam_group, iam_policy, iam_role

- terraforming.gemspec
from https://github.com/dtan4/terraforming/issues/153
https://github.com/ohler55/ox/compare/v2.2.1...v2.4.0
> Use Ox v2.4.x and Oj v2.15.x

- README.md
- lib/terraforming/resource/route_table.rb
- spec/lib/terraforming/resource/security_group_spec.rb
- spec/spec_helper.rb
- terraforming.gemspec
Current C0 test coverage is under 100%. To keep the quality of Terraforming, we have to keep test coverage 100%.
> Increase test coverage

- lib/terraforming/resource/elb.rb
- lib/terraforming/template/tf/elb.erb
- spec/lib/terraforming/resource/elb_spec.rb
Adds https://github.com/dtan4/terraforming/issues/220
> Add 'internal' argument for ELB

- .rubocop.yml
- Gemfile
Now a lot of developers contributed to Terraforming. However it seems that there lack of consistency of coding style.
I'd like to standalize the coding style in this repository.
Add RuboCop configratiton file to declare the coding style.
I also introduce [SideCI](https://sideci.com/) to check the style of pushed patch automatically.
> Introduce RuboCop & SideCI

- CHANGELOG.md
- README.md
- lib/terraforming/version.rb
- spec/lib/terraforming/cli_spec.rb
v0.9.1: https://github.com/dtan4/terraforming/pull/230
> Prepare for v0.10.0 release

- lib/terraforming/resource/iam_user.rb
- spec/lib/terraforming/resource/iam_user_spec.rb
Otherwise you get output like this:
```
~ aws_iam_user.raylu
force_destroy: "" => "false"
```
> Set `force_destroy: false` for IAM users

- CHANGELOG.md
- lib/terraforming/version.rb
Previous: [Prepare for v0.10.0 release](https://github.com/dtan4/terraforming/pull/265)
> Prepare for v0.11.0 release

- CHANGELOG.md
- README.md
- lib/terraforming/cli.rb
- lib/terraforming/version.rb
Previous: [Prepare for v0.11.0 release by dtan4 · Pull Request #286 · dtan4/terraforming](https://github.com/dtan4/terraforming/pull/286)
> Prepare for v0.12.0 release

- .rubocop.yml
- script/generate
- templates/resource_spec.rb.erb
- Add indents in message
- Make generated RSpec tests be as pending
> Modify generator behavior

- lib/terraforming/resource/kms_key.rb
- lib/terraforming/template/tf/kms_key.erb
- spec/lib/terraforming/resource/kms_key_spec.rb
- Normalize module name
- Modify testdata
> Modify kms_key implementation

- CHANGELOG.md
- README.md
- lib/terraforming/version.rb
Previous: [Prepare for v0.12.0 release by dtan4 · Pull Request #292 · dtan4/terraforming](https://github.com/dtan4/terraforming/pull/292)
> Prepare for v0.13.0 release

- lib/terraforming/template/tf/route53_record.erb
- spec/lib/terraforming/resource/route53_record_spec.rb
Recently test coverage is under 99% so that #303 lacked test.
Add testcase to compensate this
> Add Route53 record test

- .travis.yml
Both branch build and pull-request build are not required. Only pull-request build is sufficient.
> Run branch test only on master

- CONTRIBUTING.md
Versions of Ruby, Terraforming and Terraform are required to investigate problems.
> Explain how to report issue with your profile

- .travis.yml
Maybe Ruby 2.5 will be released in a day...
> Test with the latest Rubies

- .travis.yml
Remove Slack notification from Travis CI to @dtan4's private Slack
Now Slack GitHub integration supports build status notification
> Remove Slack notification

- CHANGELOG.md
- README.md
- lib/terraforming/version.rb
Bump the version to v0.17.0
Release unreleased changes before merging existing patches
> Bump the version to v0.17.0

- lib/terraforming/resource/security_group.rb
- lib/terraforming/template/tf/security_group.erb
- spec/lib/terraforming/resource/security_group_spec.rb
Include v6 permissions on sg template
> Add v6 support to sg generation
