dtan4/terraforming

- lib/terraforming/resource/db_security_group.rb
- lib/terraforming/template/tf/db_security_group.erb
- spec/lib/terraforming/resource/db_security_group_spec.rb
Terraform treats DBSecurityGroup Ingress by CIDR and EC2SecurityGroup as different things.
> Divide DBSecurityGroup Ingress

- terraforming.gemspec
[aws-sdk-ruby v2.0.36](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.0.36) is released!
This includes a fix for stubbing `nil` value.
> Update aws-sdk gem to v2.0.36

- lib/terraforming/resource.rb
- lib/terraforming/resource/db_parameter_group.rb
- lib/terraforming/resource/db_security_group.rb
- lib/terraforming/resource/db_subnet_group.rb
- lib/terraforming/resource/ec2.rb
- lib/terraforming/resource/elb.rb
- lib/terraforming/resource/rds.rb
- lib/terraforming/resource/s3.rb
- lib/terraforming/resource/security_group.rb
- lib/terraforming/resource/vpc.rb
- lib/terraforming/template/tf/db_parameter_group.erb
- lib/terraforming/template/tf/db_security_group.erb
- lib/terraforming/template/tf/db_subnet_group.erb
- lib/terraforming/template/tf/ec2.erb
- lib/terraforming/template/tf/elb.erb
- lib/terraforming/template/tf/rds.erb
- lib/terraforming/template/tf/s3.erb
- lib/terraforming/template/tf/security_group.erb
- lib/terraforming/template/tf/vpc.erb
- spec/lib/terraforming/resource/db_parameter_group_spec.rb
To avoid this error:
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.
Warnings:
* aws_db_parameter_group.default.postgres9.3: module name can only contain letters, numbers, dashes, and underscores.
This will be an error in Terraform 0.4
* aws_db_parameter_group.default.mysql5.6: module name can only contain letters, numbers, dashes, and underscores.
This will be an error in Terraform 0.4
```
> Normalize module name

- lib/terraforming.rb
- terraforming.gemspec
[AWS SDK for Ruby and Nokogiri - AWS Developer Blog - Ruby](https://ruby.awsblog.com/post/Tx2T9MFQJK7U74N/AWS-SDK-for-Ruby-and-Nokogiri)
> Version 2 of the Ruby SDK no longer relies directly on Nokogiri. Instead it has dependencies on multi_xml and multi_json. This allows you to use Ox and Oj for speed, or Nokogiri if you prefer. Additionally, the Ruby SDK will work with pure Ruby XML and JSON parsing libraries which makes distributing to varied environments much simpler.
> Introduce Oj and Ox

- lib/terraforming/resource/network_acl.rb
It does not mean that included `ingress` or `egress` is default...
- [Amazon VPCのネットワークACLについて ｜ Developers.IO](http://dev.classmethod.jp/cloud/amazon-vpc-acl/)
> Remove describe_network_acls filter

- lib/terraforming/resource/elb.rb
- lib/terraforming/template/tf/elb.erb
- spec/lib/terraforming/resource/elb_spec.rb
ELB additional attributes are supported at Terraform v0.5.0.
Include these additional attributes in generated tf and tfstate.
- [DescribeLoadBalancerAttributes - Elastic Load Balancing](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_DescribeLoadBalancerAttributes.html)
- [Implement Additional ELB Connection Attributes · hashicorp/terraform@74bfbec](https://github.com/hashicorp/terraform/commit/74bfbece69e6826836ae6820ad0cfa494d689128)
> Include ELB additional attributes

- lib/terraforming/resource/network_acl.rb
- spec/lib/terraforming/resource/network_acl_spec.rb
Rule number `32767` means default rule, which we cannot modify or delete. 
We should omit this rule.
- [aws: Don't try to modify or delete the untouchable network_acl rules. · ctiwald/terraform@d14049c](https://github.com/ctiwald/terraform/commit/d14049c8ad32a52c3d53f5eb4f48cc908b3ce644)
- [Network ACLs - Amazon Virtual Private Cloud](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_ACLs.html)
> Each network ACL includes a rule whose rule number is an asterisk. This rule ensures that if a packet doesn't match any of the other rules, it's denied. You can't modify or remove this rule.
> Omit default Network ACL rule

- lib/terraforming/resource/network_acl.rb
- spec/lib/terraforming/resource/network_acl_spec.rb
If port range from API is not set, the port in Terraform should be [0, 0]
- [aws: Force users to use from_port, to_port = 0 on network ACLs with -… · ctiwald/terraform@b888b31](https://github.com/ctiwald/terraform/commit/b888b31e08ea723cfcd1cc688f9934c9c9f601ea)
> Fix default max port number of Network ACL

- lib/terraforming/template/tf/iam_group_policy.erb
- lib/terraforming/template/tf/iam_user_policy.erb
Sometimes Terraforming generates invalid tf of IAM user policy and IAM group policy:
```
resource "aws_iam_user_policy" "hoge_policy" {
name   = "hoge_policy"
user   = "hoge"
policy = <<EOF
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"ec2:Describe*"
],
"Effect": "Allow",
"Resource": "*"
}
]
}EOF # !!!
}
```
Fix to generate valid tf always.
```
resource "aws_iam_user_policy" "hoge_policy" {
name   = "hoge_policy"
user   = "hoge"
policy = <<EOF
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"ec2:Describe*"
],
"Effect": "Allow",
"Resource": "*"
}
]
}
EOF
}
```
> Fix breaklines in policy document tf

- lib/terraforming/template/tf/route53_record.erb
- spec/lib/terraforming/resource/route53_record_spec.rb
`evaluate_target_length` :point_right: `evaluate_target_health`
> Fix Route53Record typo

- CHANGELOG.md
- lib/terraforming/resource/security_group.rb
- spec/lib/terraforming/resource/security_group_spec.rb
Add `group_id` to SecurityGroup module name to keep uniqueness, because SecurityGroup `name` field allows duplication.
> Add group id to SecurityGroup module name

- CHANGELOG.md
- lib/terraforming/template/tf/security_group.erb
- spec/lib/terraforming/resource/security_group_spec.rb
SecurityGroup resource does not allow `owner_id` argument.
[AWS: aws_security_group - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/security_group.html)
> Remove owner_id argument from SecurityGroup tf

- lib/terraforming/template/tf/ec2.erb
- lib/terraforming/template/tf/network_acl.erb
- lib/terraforming/template/tf/route53_zone.erb
- lib/terraforming/template/tf/security_group.erb
- lib/terraforming/template/tf/subnet.erb
- lib/terraforming/template/tf/vpc.erb
- spec/lib/terraforming/resource/ec2_spec.rb
- spec/lib/terraforming/resource/network_acl_spec.rb
- spec/lib/terraforming/resource/route53_zone_spec.rb
- spec/lib/terraforming/resource/security_group_spec.rb
- spec/lib/terraforming/resource/subnet_spec.rb
- spec/lib/terraforming/resource/vpc_spec.rb
Resolve #58 
AWS Resource tag name support some special characters (e.g. `:`) however HCL parser does not support them.
Quote all tag name to make Terraform-valid tag name, to accept tag name containing special chars.
> Quote tag name

- CHANGELOG.md
- lib/terraforming/resource/network_acl.rb
- lib/terraforming/template/tf/network_acl.erb
- spec/lib/terraforming/resource/network_acl_spec.rb
- terraforming.gemspec
Network ACL `subnet_ids` argument is supported from Terraform v0.5.3
> Include Network ACL subnet ids

- lib/terraforming/resource/security_group.rb
- lib/terraforming/template/tf/security_group.erb
In version 0.6.0 of terraform, ingress/egress rules that are both self referencing and contain a CIDR block are sometimes combined in the tfstate output. If the resources are separate in the .tf template, this causes `terraform plan` to show a large diff. This PR will combine rules that have the same protocol and port range, and that are both self referencing and contain a CIDR block. This effects both .tf and .tfstate output. This fixes https://github.com/dtan4/terraforming/issues/92.
> Security group ingress/egress fix

- lib/terraforming/resource/ec2.rb
- spec/lib/terraforming/resource/ec2_spec.rb
from #103 
Though EC2 instance does not have any attached EBS volumes, it goes well without any exception.
> Add a guard not to generate empty block devices

- lib/terraforming/resource/elasti_cache_cluster.rb
- lib/terraforming/template/tf/elasti_cache_cluster.erb
- spec/lib/terraforming/resource/elasti_cache_cluster_spec.rb
Close #107 
Stop including port parameter in ElastiCache cluster at any time. It raises error with like Redis cluster.
> Stop including ElastiCache cluster port at any time

- README.md
- lib/terraforming/cli.rb
- spec/lib/terraforming/cli_spec.rb
- spec/spec_helper.rb
Close #113 
Terraforming 0.1.6 does not provide the way to overwrite existing tfstate in itself. However, due to the design of shell redirect, users cannot overwrite tfstate easily.
Add `--overwrite` option to overwrite tfstate at once.
```bash
$ terraforming s3 --tfstate --merge .terraform/terraform.tfstate --overwrite
```
> Overwrite existing tfstate by --overwrite option

- lib/terraforming/resource/route53_zone.rb
- spec/lib/terraforming/resource/route53_zone_spec.rb
Close #114 
Some Route53 _private_ hosted zones return empty delegation set. It causes nil exception at `#name_servers_of` method.
Return empty Array if `delegation_set` is nil
> Treat Route53 hosted zone with empty delegation set

- lib/terraforming/resource/route53_zone.rb
- lib/terraforming/template/tf/route53_zone.erb
- spec/lib/terraforming/resource/route53_zone_spec.rb
Terraform v0.6.3 has `vpc_id` and `vpc_region` parameters in Route53 hosted zone.
- [AWS: aws_route53_zone - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/route53_zone.html)
> Include associated VPC parameters in Route53 hosted zone

- lib/terraforming/resource/db_security_group.rb
- spec/lib/terraforming/resource/db_security_group_spec.rb
Close #115 
DB security group `ingress` parameter is _required_ parameter, however, _default_ DB security group has no ingress rule. It causes error by `terraform plan` with generated default DB security group.
Exclude default DB security group (= with empty ingress rules) from generating result.
- [AWS: aws_db_security_group - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/db_security_group.html)
- (It seems that document is wrong at [1d77a258](https://github.com/hashicorp/terraform/tree/1d77a258d08e9bff856d299b52a755b1250fb415) ) ...
> Exclude DB security group with empty ingress rules

- lib/terraforming/resource/s3.rb
- spec/lib/terraforming/resource/s3_spec.rb
- terraforming.gemspec
Close #116 
Terraforming v0.1.6 tries to fetch S3 buckets in the different region from `AWS_REGION`, and it fails.
Export S3 buckets only in the same region as `AWS_REGION`.
- https://github.com/aws/aws-sdk-ruby/pull/899
> Export buckets only in the same region

- lib/terraforming/resource/iam_user.rb
- lib/terraforming/template/tf/iam_user.erb
- spec/lib/terraforming/resource/iam_user_spec.rb
Close #123 
Terraform does not allow module name with `.` (dots), like below.
```
resource "aws_iam_user" "david.raistrick" {
name = "david.raistrick"
path = "/"
}
```
Replace dots to hyphen in IAM user module
```
resource "aws_iam_user" "david-raistrick" {
name = "david.raistrick"
path = "/"
}
```
> Normalize module name of IAM user

- lib/terraforming/resource/ec2.rb
- lib/terraforming/template/tf/ec2.erb
- spec/lib/terraforming/resource/ec2_spec.rb
Hi,
I added a missing key `monitoring` for `ec2` resource.
The state of the API response could be `disabled`, `disabling`, `enabled`, `pending`.
I implemented this to output `monitoring  = true` only for `enabled` state.
refs:
- http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Types/Monitoring.html
- https://www.terraform.io/docs/providers/aws/r/instance.html#monitoring
> Export ec2 instance monitoring state

- lib/terraforming/template/tf/ec2.erb
- spec/lib/terraforming/resource/ec2_spec.rb
Close #131 
Exclude `iops` field from EC2 instance tf when the device is `standard` type (= does not have `iops` parameter in itself)
> Exclude iops if device type is standard

- lib/terraforming/resource/route53_record.rb
- lib/terraforming/template/tf/route53_record.erb
- spec/lib/terraforming/resource/route53_record_spec.rb
terraform use `*.example.com`, but terraforming(aws-sdk-ruby) generate `\052.example.com`.
---
see https://forums.aws.amazon.com/thread.jspa?messageID=212732
> Fix wildcard record format when `terraforming r53r`

- spec/spec_helper.rb
Fixes 'multi_formatter.rb:17:in `new': wrong number of arguments (2 for 0..1) (ArgumentError)' error when running 'bundle exec rake'.
> Use the .new method on MultiFormatter

- lib/terraforming/template/tf/ec2.erb
On master:
```
$ terraforming ec2 > ec2.tf
$ terraform plan .
Error loading config: Error parsing ec2.tf: Line 2817, column 20: syntax error
```
There's a line like:
```
source_dest_check =
```
in the `.tf` file.
On this branch:
```
$ terraforming ec2 > ec2.tf
$ terraform plan .
There are warnings and/or errors related to your configuration. Please
fix these before continuing.
```
(the errors here are due to duplicate names in our AWS account, but the parser finishes)
> Ignore source_dest_check if nil

- lib/terraforming/resource/route_table.rb
- lib/terraforming/template/tf/route_table.erb
- spec/lib/terraforming/resource/route_table_spec.rb
As mentioned in #145, current route_table support is incomplete and incorrect:
* it does not support tags in TF state
* it does not support routes in TF state
* it does not support propagating virtual gateways at all
* it exports routes that should not be exported (local gateway id and a few other cases)
This PR has been tested on a relatively large account and it seems to have worked correctly: we have exported a few dozen networks across 5 VPCs with exported routes, etc. And, based on the live experience with the new code, I have updated route_table specs to actually expect correct results as well.
> Improved route_table support

- lib/terraforming/resource/route_table_association.rb
- lib/terraforming/template/tf/route_table_association.erb
- spec/lib/terraforming/resource/route_table_association_spec.rb
As explained in #147, there is a way for terraforming to generate tfstate for tfa that would cause terraform to crash. This PR fixes the issue.
> Skip implicit route table associations when generating tfstate

- spec/lib/terraforming/resource/auto_scaling_group_spec.rb
- terraforming.gemspec
To avoid unexpected test failures due to the new version of aws-sdk, we decided to fix the version fo aws-sdk.
> Use aws-sdk v2.2.5

- lib/terraforming/template/tf/auto_scaling_group.erb
- spec/lib/terraforming/resource/auto_scaling_group_spec.rb
Multiple tags in AutoScaling Group are exported to this tf:
```
tag {
key   = "Name"
value = "piyo"
propagate_at_launch = true
key   = "app"
value = "sample"
propagate_at_launch = true
}
```
These should be exported like this:
```
tag {
key   = "Name"
value = "piyo"
propagate_at_launch = true
}
tag {
key   = "app"
value = "sample"
propagate_at_launch = true
}
```
Modify code, and add test fixture and tests .
> Modify AutoScaling Group tags

- lib/terraforming/resource/auto_scaling_group.rb
Currently, terraforming can't generate over 50 AutoScaling Groups.
This PR fix it like EC2.
> Retrieve full list of AutoScaling Groups

- contrib/zsh-completion/_terraforming
I made zsh completion for terraforming. Thanks for your useful tool!
My test environment is:
* OS
```bash
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21
```
* zsh
```bash
$ zsh --version
zsh 5.2 (x86_64-apple-darwin15.0.0)
```
The example outputs of this zsh completion are:
* output1 (show subcommands)
```bash
$ terraforming<tab>
asg    -- AutoScaling Group
dbpg   -- Database Parameter Group
dbsg   -- Database Security Group
dbsn   -- Database Subnet Group
ec2    -- EC2
ecc    -- ElastiCache Cluster
ecsn   -- ElastiCache Subnet Group
eip    -- EIP
elb    -- ELB
help   -- Describe available commands or one specific command
iamg   -- IAM Group
iamgm  -- IAM Group Membership
iamgp  -- IAM Group Policy
iamip  -- IAM Instance Profile
iamp   -- IAM Policy
iamr …
```
> Add zsh-completion

- lib/terraforming/resource/elasti_cache_cluster.rb
- lib/terraforming/template/tf/elasti_cache_cluster.erb
- spec/lib/terraforming/resource/elasti_cache_cluster_spec.rb
A redis elasticache cluster can only have one node (according to the terraform documentation), so we can use the cache_nodes[0].endpoint.port to populate the port value.
> Add elasticache redis port

- lib/terraforming/resource/subnet.rb
- spec/lib/terraforming/resource/subnet_spec.rb
I have multiple VPCs and the subnets names are the same, which is causing an issue when I try to import them with terraforming.
> Add subnet id to the subnet resource name, because two subnets can have the same name

- lib/terraforming/resource/route53_record.rb
- spec/lib/terraforming/resource/route53_record_spec.rb
Otherwise terraform wants to change all weight "" => "-1" which is a noop, it just changes the terraform.tfstate actually.
The official documentation says
https://www.terraform.io/docs/providers/aws/r/route53_record.html
```
Note: The weight attribute uses a special sentinel value of -1 for a default in
Terraform. This allows Terraform to distinquish between a 0 value and an empty
value in the configuration (none specified). As a result, a weight of -1 will
be present in the statefile if weight is omitted in the configuration.
```
> [route53 records] Default weight should be "-1"

- lib/terraforming/resource/iam_policy.rb
- lib/terraforming/template/tf/iam_policy.erb
- spec/lib/terraforming/resource/iam_policy_spec.rb
If the existing policies have descriptions, they need to be included in the terraforming output or else terraform will attempt to destroy and recreate the policies, which could break if they're attached to other resources.
> Include description field for IAM Policies

- .travis.yml
- Gemfile
- README.md
- terraforming.gemspec
Recently Travis CI fails (https://travis-ci.org/dtan4/terraforming/builds/126665204) because the latest Guard [droped Ruby 2.1 & 2.0 support](https://github.com/guard/guard/tree/cf51959d9c9bdcb6cab0b66aeb9735d76d4f2457).
Remove guard dependencies from gemspec. Guard family is not necessary for some developers.
And also, drop Ruby 2.0 support from the next version. Ruby 2.0 is [no longer supported officially (EOL)](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/).
> Fix travis guard

- terraforming.gemspec
https://github.com/aws/aws-sdk-ruby/releases/tag/v2.3.0
> Use aws-sdk v2.3.x

- terraforming.gemspec
There is no reason to restrict Rake version...
> Do not specify Rake version

- lib/terraforming/resource/iam_group_policy.rb
- lib/terraforming/resource/iam_role_policy.rb
- lib/terraforming/resource/iam_user_policy.rb
- lib/terraforming/template/tf/iam_group_policy.erb
- lib/terraforming/template/tf/iam_role_policy.erb
- lib/terraforming/template/tf/iam_user_policy.erb
- spec/lib/terraforming/resource/iam_group_policy_spec.rb
- spec/lib/terraforming/resource/iam_role_policy_spec.rb
- spec/lib/terraforming/resource/iam_user_policy_spec.rb
AWS allows different inline policies to have the same name as long as they belong to different resources (e.g. different user, role, or group) - so the terraform resource name ought to be more unique than just copying the inline policy name.
This change sets the terraform resource name as the combination of the resource and policy names, which is more verbose but prevents duplicate resource errors.
> [IAM]: Prefix inline policy terraform name to prevent `resource repeated multiple times` errors

- lib/terraforming/resource/security_group.rb
- spec/lib/terraforming/resource/security_group_spec.rb
As described in #205, the purpose of this patch is to provide a better out of
the box security group naming convention. The current approach
`[security-group-id]-[security-group-name]` is not very convenient, since we
don't know the security group id in advance. The only reason it's useful is
that it provides 100% unique security group resoruce ids.
A better approach is to use security group names for EC2 Classic, and vpc_id as
prefix for VPC security groups.
This also keeps the unique resource ids but makes them easier to handle
and read.
> [sg] Simplify generated security-group names

- lib/terraforming/resource/elb.rb
- lib/terraforming/template/tf/elb.erb
- spec/lib/terraforming/resource/elb_spec.rb
ELB `access_logs` was introduces at [Terraform v0.6.7](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#067-november-23-2015).
- [AWS: aws_elb - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/elb.html)
> Add access_logs attribute to ELB

- lib/terraforming.rb
see https://github.com/dtan4/terraforming/issues/153
NameError will occur under the following conditions.
* OS X
* ruby 2.2.4p230 (rbenv)
* ox 2.4.1 ( **MUST** Only 2.4.1 is installed.)
ox 2.4.1 install .bundle file to `/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0/ox-2.4.1/ox.bundle`.
When `require "ox"` executed, will try to load  above file.
But correct file is `.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/ox-2.4.1/lib/ox.rb`
This problem does not occur in the environment in which is installed multiple version ox.
Please merge if there is no problem.
Thanks.
> Fix ox load error

- lib/terraforming/cli.rb
Both "iamp" and "iampa" were listed as "iamp" in the help output, which caused the "export all" example in the readme to mistakenly overwrite "iamp" output.
> Fix name of "iampa" subcommand in CLI help output.

- lib/terraforming/template/tf/eip.erb
- spec/lib/terraforming/resource/eip_spec.rb
Close #233 
`network_interface_id` is invalid. The correct key name is `network_interface`.
- [AWS: aws_eip - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/eip.html#network_interface)
> Fix network_interface naming in EIP

- lib/terraforming/resource/iam_group_membership.rb
https://github.com/dtan4/terraforming/commit/2e55beec569e5e4937f1a655dbc59e7c6c3a6804#diff-590760686c68c2507617371c9719e4d3 paginates groups but not their members
> Paginate group membership

- lib/terraforming/resource/iam_policy_attachment.rb
This branch is based on stripe/paginate_group_members so includes the changes in #248.
We generate only Local-scoped policies in iamp, which is fine. We need to generate both Local- and AWS-scoped attachments though, so that users/groups/roles with AWS-scoped policies (such as `arn:aws:iam::aws:policy/AmazonS3FullAccess`) are generated.
> AWS-scoped IAM policy attachments

- README.md
This seems like a really bad idea, at least the way it's described here. In my local, fairly empty directory, `find . -type f | xargs wc -l | grep '1 .'` returns:
```
1 ./.git/COMMIT_EDITMSG
1 ./.git/description
1 ./.git/HEAD
1 ./.git/logs/HEAD
1 ./.git/logs/refs/heads/master
11 ./.git/objects/42/14eb21b7be0687ccb477ec1e5a8ecdf7711b05
1 ./.git/objects/5e/001b34698fe2cd0da484fa9ab896e42df155b9
1 ./.git/refs/heads/master
1 ./.gitignore
1 ./asg.tf
1 ./dbsg.tf
1 ./dbsn.tf
1 ./ec2.tf
1 ./ecc.tf
1 ./ecsn.tf
1 ./eip.tf
1 ./elb.tf
1 ./iamp.tf
1 ./iamrp.tf
1 ./igw.tf
1 ./lc.tf
1 ./nacl.tf
1 ./nif.tf
1 ./r53r.tf
1 ./r53z.tf
1 ./rds.tf
1 ./rs.tf
1 ./rt.tf
1 ./rta.tf
1 ./sn.tf
1 ./sqs.tf
1 ./vgw.tf
1 ./vpc.tf
```
As you can see, it is deleting _anything_ in the folder with 1 line in it. Not only …
> Remove commands to delete empty files in export

- lib/terraforming/template/tf/ec2.erb
- spec/lib/terraforming/resource/ec2_spec.rb
Close https://github.com/dtan4/terraforming/issues/266
`iops` of EC2 `root_block_device` and `ebs_block_device` must be set with `io1` (Provisioned IOPS SSD) volume.
Generate `iops1` only when the `volume_type` is `io1`.
- [AWS: aws_instance - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/instance.html)
> Generate iops field only with io1 volume

- README.md
- lib/terraforming.rb
- lib/terraforming/cli.rb
- lib/terraforming/resource/cloud_watch_alarm.rb
- lib/terraforming/template/tf/cloud_watch_alarm.erb
- spec/lib/terraforming/cli_spec.rb
- spec/lib/terraforming/resource/cloud_watch_alarm_spec.rb
i refactored https://github.com/dtan4/terraforming/pull/182 as i saw no activity on it.
Hope you can merge it in 😄
> Cloudwatch alarm support

- .travis.yml
- lib/terraforming.rb
- lib/terraforming/cli.rb
- terraforming.gemspec
Ox and Oj installations sometimes occur error by environment. It should be that users can choose gems to use. For example, some users use built-in json gem, others user oj and ox gems for speed.
Remove dependency of oj gem and introduce [multi_json](https://github.com/intridea/multi_json) gem. multi_json gem loads the fastest JSON gem from installed gems automatically.
In addition, ox gem dependency is also removed. aws-sdk gem loads the fastest gem from installed gems automatically.
> Remove native extension gems and use wrapper gem

- lib/terraforming/resource/ec2.rb
- lib/terraforming/template/tf/ec2.erb
- spec/lib/terraforming/resource/ec2_spec.rb
Fix hardcoded value for associate_public_ip_address attribute from "true" to dynamic based on public_ip_address state.
> Fix associate_public_ip_address attr for EC2

- lib/terraforming.rb
- lib/terraforming/cli.rb
- lib/terraforming/resource/alb.rb
- lib/terraforming/template/tf/alb.erb
- spec/lib/terraforming/cli_spec.rb
- spec/lib/terraforming/resource/alb_spec.rb
Recently we migrated our CLB to ALB. We use [elastic-load-balancing-tools](https://github.com/aws/elastic-load-balancing-tools) for migration, so new ALBs have not been written as Terraform code yet.
Support ALB code generation.
> Support ALB (Application Load Balancer)

- CONTRIBUTING.md
- Gemfile
- README.md
- script/generate
- templates/resource.erb.erb
- templates/resource.rb.erb
- templates/resource_spec.rb.erb
To add new resource to Terraforming, developers have to...
- Create 3 new files 
- `lib/terraforming/resource/resource.rb`
- `lib/terraforming/template/tf/resource.erb`
- `spec/lib/terraforming/resource/resource_spec.rb`
- Modify 3 files
- `lib/terraforming.rb`
- `lib/terraforming/cli.rb`
- `spec/lib/terraforming/cli_spec.rb`
It's troublesome to add them by hand.
Preapare skeleton generator script. It creates 3 new files and guides how to modify other files.
> Prepeare code skeleton generator

- lib/terraforming/resource/efs_file_system.rb
- lib/terraforming/resource/eip.rb
- lib/terraforming/resource/elasti_cache_cluster.rb
- lib/terraforming/resource/elasti_cache_subnet_group.rb
- lib/terraforming/resource/iam_group.rb
- lib/terraforming/resource/iam_group_membership.rb
- lib/terraforming/resource/iam_group_policy.rb
- lib/terraforming/resource/iam_instance_profile.rb
- lib/terraforming/resource/iam_policy.rb
- lib/terraforming/resource/iam_policy_attachment.rb
- lib/terraforming/resource/iam_role.rb
- lib/terraforming/resource/iam_role_policy.rb
- lib/terraforming/resource/iam_user_policy.rb
- lib/terraforming/template/tf/eip.erb
- lib/terraforming/template/tf/elasti_cache_cluster.erb
- lib/terraforming/template/tf/elasti_cache_subnet_group.erb
- lib/terraforming/template/tf/elastic_filesystem.erb
- lib/terraforming/template/tf/iam_group.erb
- lib/terraforming/template/tf/iam_group_membership.erb
- lib/terraforming/template/tf/iam_instance_profile.erb
- lib/terraforming/template/tf/iam_policy.erb
- lib/terraforming/template/tf/iam_policy_attachment.erb
- lib/terraforming/template/tf/iam_role.erb
- lib/terraforming/template/tf/redshift.erb
> Normalize all resource names in tf and tfstate files

- spec/lib/terraforming/resource/security_group_spec.rb
Close #174 
Rewrite #173 
#173 provides a solution for #174, however, the branch is too old to merge into current master. I tried to merge by hand, but it was so hard...
I tested the given testcase, then current Terraforming generated correct tf. 
```hcl
resource "aws_security_group" "test-terraform" {
name = "test-terraform"
description = "Test the terraform sg"
ingress {
from_port = 7777
to_port = 7777
self = 1
protocol = "tcp"
security_groups = ["sg-1234abcd"]
}
}
```
Add the above testcase.
> Add testcase with self inbound

- lib/terraforming/resource/route53_record.rb
- lib/terraforming/template/tf/route53_record.erb
- spec/lib/terraforming/resource/route53_record_spec.rb
This PR is for a couple of changes for resources of `aws_route53_record` type:
* `weight` should be wrapped in a `weighted_routing_policy {}` block.
* Added support for routing policies other than weighted (i.e. latency and geolocation)
* Don't use duplicate resource names; differentiate similarly-named resource names with a counter.
> Fixes for route53_records

- lib/terraforming/resource/eip.rb
- spec/lib/terraforming/resource/eip_spec.rb
For EC2-Classic, the allocation_id is nil, which causes an error, so the ID and the module name should be derived from IP address rather than the allocation_id.
> Fix support for EIP in EC2-Classic

- lib/terraforming/resource/security_group.rb
- lib/terraforming/template/tf/security_group.erb
- spec/lib/terraforming/resource/security_group_spec.rb
The security groups terraforming was generating were missing prefix lists. This adds them, as well as some tests.
> Add prefix lists to security groups configuration

- lib/terraforming/resource/route53_record.rb
- spec/lib/terraforming/resource/route53_record_spec.rb
Normalize '-052' to 'wildcard'.
See https://github.com/dtan4/terraforming/issues/347
This renames the title of an `aws_route53_record` with a wildcard to a string which can be reused without having to modify the output of `terraform r53r (--tfstate)`.
```
resource "aws_route53_record" "-052-example-net-CNAME" {
zone_id = "XYZ"
name    = "*.example.net"
type    = "CNAME"
records = ["example.net."]
ttl     = "1800"
}
```
->
```
resource "aws_route53_record" "wildcard-example-net-CNAME" {
zone_id = "XYZ"
name    = "*.example.net"
type    = "CNAME"
records = ["example.net."]
ttl     = "1800"
}
```
> Rename title of aws_route53_record with wildcard.

- lib/terraforming/template/tf/network_acl.erb
- spec/lib/terraforming/resource/network_acl_spec.rb
Resolve #339
Network ACL Ingress/Egress rule can specify [ICMP code and type](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-types).
Terraform also specify them as its parameters.
Generate Network ACL tf file with `icmp_code` and `icmp_type` fields.
- [AWS: aws_network_acl - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/network_acl.html)
> Add icmp_code and icmp_type to NACL tf

- .travis.yml
[Official support of Ruby 2.1 has ended](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/)
To improve CI speed, drop tests with Ruby 2.1 which is no longer supported.
> Drop Ruby 2.1 from CI

- README.md
- lib/terraforming/resource/kms_key.rb
- spec/lib/terraforming/resource/kms_key_spec.rb
Fix #361 
[`Aws::KMS::Client#get_key_rotation_status`](http://docs.aws.amazon.com/sdkforruby/api/Aws/KMS/Client.html#get_key_rotation_status-instance_method) does not support external origin key. In addition, Terraform does not support it too.
Ignore external origin key by `terraforming kmsk [--tfstate]` command.
> Ignore external key

- lib/terraforming/resource/route53_record.rb
- lib/terraforming/template/tf/route53_record.erb
- spec/lib/terraforming/resource/route53_record_spec.rb
The attributes about DNS failiover (the following 2 attributes) are missing in the exported Route53 tf and tfstate files, so this PR adds them.
* "failover_routing_policy"
* "health_check_id"
> Add failover attributes to Route53 record.

- lib/terraforming/resource/iam_instance_profile.rb
- lib/terraforming/template/tf/iam_instance_profile.erb
- spec/lib/terraforming/resource/iam_instance_profile_spec.rb
Fix issue #374 .
Because the "roles" argument in aws_iam_instance_profile is deprecated,
use "role" instead in tf and tfstate.
cf: [AWS: aws_iam_instance_profile - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/iam_instance_profile.html)
In addition, remove the test case with 0 role. In this case, terraform will output the following error.
```
Error applying plan:
1 error(s) occurred:
* aws_iam_instance_profile.test_profile: 1 error(s) occurred:
* aws_iam_instance_profile.test_profile: Either `role` or `roles` (deprecated) must be specified when creating an IAM Instance Profile
```
> Fix iam instance profile

- lib/terraforming/resource/kms_key.rb
- lib/terraforming/template/tf/kms_key.erb
- spec/lib/terraforming/resource/kms_key_spec.rb
Fix #373 
`ENCRYPT/DECRYPT` is invalid for KMS key usage. Only `ENCRYPT_DECRYPT` is acceptable.
Generate tf & tfstate with the value `ENCRYPT_DECRYPT`. Stop replacing `_` to `/`.
- [CreateKey - AWS Key Management Service](http://docs.aws.amazon.com/kms/latest/APIReference/API_CreateKey.html)
> Use ENCRYPT_DECRYPT as KMS key usage

- lib/terraforming/resource/security_group.rb
In some cases, the security group name in a permission may be nil if it is a cross-account permission. This fix allows terraforming to fall back to using the security group id.
> Fix cross-account security group reference

- spec/lib/terraforming/resource/efs_file_system_spec.rb
- terraforming.gemspec
Upgrade EFS code to support the latest EFS client, and specify the dependency version to use aws-sdk-efs 1.13.0 or above.
Current code fails the test
```
Failures:
1) Terraforming::Resource::EFSFileSystem.tf should generate tf
Failure/Error: client.stub_responses(:describe_file_systems, file_systems: [efs_description_0, efs_description_1])
ArgumentError:
parameter validator found 2 errors:
- missing required parameter params[:file_systems][0][:tags]
- missing required parameter params[:file_systems][1][:tags]
2) Terraforming::Resource::EFSFileSystem.tfstate should generate tfstate
Failure/Error: client.stub_responses(:describe_file_systems, file_systems: [efs_description_0, efs_description_1])
ArgumentError:
parameter validator found 2 errors:
- missing required parameter …
```
> Support the latest EFS client

- .travis.yml
Run tests with the latest and currently supported Rubies in Travis CI
Ruby 2.3 is [end-of-life (EOL) officially](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/), however, macOS still uses this in default.
Some users run Terraforming with system Ruby (without installing the latest Ruby or using rbenv), so Terraforming should also support macOS' default Ruby.
```sh-session
$ /usr/bin/ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```
The tool should support the latest Ruby in its lifetime. Additionally, it doesn't have to support the old Rubies once they became end-of-life (EOL).
[Ruby Maintenance Branches](https://www.ruby-lang.org/en/downloads/branches/)
> Use the latest and supported Rubies

- lib/terraforming/resource/elasti_cache_cluster.rb
- lib/terraforming/template/tf/elasti_cache_cluster.erb
- spec/lib/terraforming/resource/elasti_cache_cluster_spec.rb
I think it's good to render `notification_topic_arn` on .tf file and .tfstate file. Because I'm using terraforming with Terraform CLI tool with `import` subcommand.
In that situation, I work according to the below instructions.
- Execute `terraforming ecc`
- Cut and paste (or process the output by a script) a target cluster TF configuration to a new .tf file.
- Run `terraform import module.elasticache_redis.aws_elasticache_cluster.foo foo` to import the actual resource into tfstate file.
- I confirm that there are no diffs by run `terraform plan` command.
If the actual resource has a notification configuration, then the `terrafrom plan` generates the following output.
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ …
```
> Render notification_topic_arn when exporting ElastiCache clusters

- lib/terraforming/template/tf/iam_instance_profile.erb
While running terraforming iamip  I ended up following error. This fix worked for me
```
$terraforming iamip 
...//log
1: from (erb):1:in `each'
(erb):5:in `block in apply_template': undefined method `role_name' for nil:NilClass (NoMethodError)
```
> iamp-nil-check

- README.md
- lib/terraforming/cli.rb
- lib/terraforming/resource/dynamo_db.rb
- spec/lib/terraforming/cli_spec.rb
- spec/lib/terraforming/resource/dynamo_db_spec.rb
- Replace `Dynamo DB` to `DynamoDB`
- Rename Symbol `DynamoDb` to `DynamoDB`
"DynamoDB" is the correct notation.
https://aws.amazon.com/dynamodb/
> Rename Symbol of DynamoDB
